"""Local content for every city and service. Edit freely; run `bash build.sh` after."""
CITIES = {
 "spring": dict(name="Spring", county="Harris", zips="77373, 77379, 77388, 77389", lat=30.0799, lon=-95.4172,
  areas=["Old Town Spring", "Louetta Road corridor", "Cypresswood", "Gleannloch Farms", "Augusta Pines", "Spring Creek Greenway area"],
  housing="Spring runs from the antique shops of Old Town Spring to large 1990s and 2000s subdivisions with two-car garages and big backyards, so we see everything from garage purges to backyard structures.",
  jobs="garage and storage cleanouts, trampoline and playset teardowns, post-move leftovers, and furniture or appliance pickups in the subdivisions off Louetta and Spring Cypress",
  note="Spring is our home base, so it is the area we know best."),
 "klein": dict(name="Klein", county="Harris", zips="77379, 77388, 77389", lat=30.0316, lon=-95.5272,
  areas=["Klein Collins area", "Spring Cypress Road", "Kuykendahl Road", "Louetta Road", "Ponderosa Forest"],
  housing="Klein is a mix of established family neighborhoods and newer builds along Spring Cypress and Louetta, with plenty of detached garages, sheds and backyard sports equipment.",
  jobs="backyard trampoline and basketball goal removal, garage cleanouts, remodel debris and moving-out leftovers",
  note="We regularly serve the Klein area as part of our Spring-based crew."),
 "the-woodlands": dict(name="The Woodlands", county="Montgomery", zips="77380, 77381, 77382, 77384, 77385", lat=30.1658, lon=-95.4613,
  areas=["Town Center and the Waterway", "Sterling Ridge", "Alden Bridge", "Panther Creek", "Grogan's Mill", "Creekside Park"],
  housing="The Woodlands has large wooded lots, big homes, finished garages and a steady stream of renovations, relocations and estate transitions.",
  jobs="renovation and remodel debris, estate and downsizing cleanouts, big garage cleanouts, and furniture removal ahead of moves",
  note="We handle both homes and condos across The Woodlands townships."),
 "humble": dict(name="Humble", county="Harris", zips="77338, 77346, 77396", lat=29.9988, lon=-95.2622,
  areas=["Atascocita", "Lake Houston area", "Eastex Freeway (US 59) corridor", "Fall Creek", "Kingwood border"],
  housing="Humble and nearby Atascocita are made up of family subdivisions, lake-area homes and apartments along US 59, so we do plenty of moves, garage cleanouts and storm-season cleanups.",
  jobs="storm and flood-damaged furniture removal, garage cleanouts, apartment move-outs and yard debris",
  note="Humble and the Lake Houston area are part of our Spring-based service area."),
 "tomball": dict(name="Tomball", county="Harris", zips="77375, 77377", lat=30.0972, lon=-95.6161,
  areas=["Historic downtown Tomball", "Tomball Parkway (SH 249)", "Lake Woodlands border", "Medical Center area", "FM 2920 corridor"],
  housing="Tomball combines a historic Main Street district with fast-growing subdivisions and acreage on the edges of town, so jobs range from small-town estate cleanouts to big yard-and-outbuilding hauls.",
  jobs="estate and downsizing cleanouts, barn and shed cleanouts, fence and deck debris, and large garage cleanouts",
  note="Tomball is our home base for this location."),
 "magnolia": dict(name="Magnolia", county="Montgomery", zips="77354, 77355", lat=30.2091, lon=-95.7508,
  areas=["Downtown Magnolia", "FM 1488 corridor", "Magnolia Parkway", "Rural acreage west of town", "Stagecoach area"],
  housing="Magnolia has a lot of rural acreage, ranch-style properties and newer subdivisions, which means barns, outbuildings, fencing and equipment alongside regular household junk.",
  jobs="acreage and barn cleanouts, fence removal, storm debris, and whole-property cleanups",
  note="We make regular trips out to Magnolia and the surrounding acreage."),
 "pinehurst": dict(name="Pinehurst", county="Montgomery", zips="77362", lat=30.1527, lon=-95.6958,
  areas=["Pinehurst town center", "Near Magnolia", "Grand Parkway corridor", "Rural properties", "FM 1774 area"],
  housing="Pinehurst is a smaller, quieter community of homes on larger lots, with lots of wooded property where yard waste, old sheds and storage buildings pile up.",
  jobs="yard waste and brush hauls, shed teardowns, garage cleanouts and furniture pickups",
  note="Pinehurst sits between Tomball and Magnolia, so it is an easy stop on our route."),
 "cypress": dict(name="Cypress", county="Harris", zips="77429, 77433", lat=29.9691, lon=-95.6972,
  areas=["Bridgeland", "Towne Lake", "Fairfield", "Cypress Creek Lakes", "Barker Cypress corridor", "Cypress-Fairbanks area"],
  housing="Cypress is dominated by big master-planned communities like Bridgeland and Towne Lake, with newer homes, large garages, backyard play equipment and constant moving activity.",
  jobs="trampoline and playset removal, move-in and move-out cleanouts, garage purges and new-build debris",
  note="Cypress is our home base for this location."),
 "jersey-village": dict(name="Jersey Village", county="Harris", zips="77040, 77065", lat=29.8897, lon=-95.5699,
  areas=["Jersey Village city center", "US 290 corridor", "Jones Road area", "Near Hwy 6", "Cypress Station"],
  housing="Jersey Village is an established northwest Houston community of mid-century and later homes, townhomes and commercial space along US 290.",
  jobs="furniture and appliance removal, garage cleanouts, small commercial cleanouts and flood-damaged items",
  note="Jersey Village is a short drive from our Cypress crew."),
 "hockley": dict(name="Hockley", county="Waller", zips="77447", lat=30.0291, lon=-95.8508,
  areas=["Hockley town", "FM 2920 corridor", "Hegar Road area", "Rural acreage", "Hwy 290 west"],
  housing="Hockley is mostly rural acreage, ranch properties and older homesteads, so barns, old equipment, fencing and years of accumulated storage are common.",
  jobs="barn and outbuilding cleanouts, acreage cleanups, appliance and furniture removal, and fence debris",
  note="We travel out to Hockley and the surrounding rural area regularly."),
 "katy": dict(name="Katy", county="Harris, Fort Bend and Waller", zips="77449, 77450, 77493, 77494", lat=29.7858, lon=-95.8244,
  areas=["Cinco Ranch", "Katy Mills area", "Grand Parkway corridor", "Mason Road area", "Old Katy Road", "Park Row"],
  housing="Katy is a fast-growing suburb of newer subdivisions, planned communities and larger family homes, so garage cleanouts, move-outs and renovation debris are the most common jobs.",
  jobs="garage and attic cleanouts, move-out cleanups, furniture and appliance removal, and renovation debris",
  note="Katy is a short drive from our Cypress crew."),
 "college-station": dict(name="College Station", county="Brazos", zips="77840, 77843, 77845", lat=30.6280, lon=-96.3344,
  areas=["Near Texas A&M University", "Northgate", "Wolf Pen Creek", "Pebble Creek", "Castlegate", "Texas Avenue corridor"],
  housing="College Station is shaped by Texas A&M University: apartments, student rentals and a heavy move-out rhythm at the end of each semester, plus family homes toward Pebble Creek and Castlegate.",
  jobs="student and apartment move-outs, furniture and mattress removal, rental turnovers and garage cleanouts",
  note="College Station is our home base for this location."),
 "bryan": dict(name="Bryan", county="Brazos", zips="77801, 77802, 77803, 77807, 77808", lat=30.6744, lon=-96.3699,
  areas=["Downtown Bryan", "Texas Avenue", "Villa Maria Road", "Near Coulter Field", "East Bryan neighborhoods"],
  housing="Bryan blends historic downtown buildings and older neighborhoods with newer subdivisions, rental properties and commercial space.",
  jobs="rental turnovers, estate cleanouts, appliance and furniture removal, and light commercial cleanouts",
  note="Bryan is right next door to College Station, so we serve both on the same route."),
 "navasota": dict(name="Navasota", county="Grimes", zips="77868", lat=30.3880, lon=-96.0877,
  areas=["Old Town Navasota", "Texas 6 corridor", "Navasota River area", "Rural Grimes County", "Washington Avenue"],
  housing="Navasota is a small historic town surrounded by farmland and rural homesteads, so jobs often involve outbuildings, old equipment and whole-property cleanups.",
  jobs="estate and farm property cleanouts, barn and shed removal, appliance pickups and yard debris",
  note="We make trips out to Navasota and rural Grimes County."),
}

SERVICES = [
 dict(slug="junk-removal", name="Junk Removal", blurb="Furniture, boxes, old household items and general junk, hauled away.", icon="01",
  intro="Whatever is cluttering your home, garage or yard, we load it, haul it and sweep up. No sorting, no trips to the dump, no heavy lifting for you.",
  items=["Household junk and old belongings", "Furniture and mattresses", "Boxes, bins and storage", "Garage and attic cleanouts", "Yard junk and old equipment", "Single items to full truckloads"],
  faq=[("How do I get a price?", "Text photos to (346) 413-9644 or use the form. We give a firm price before we start."), ("Can you take just one item?", "Yes. Single-item pickups are welcome."), ("Do I need to be home?", "Not always. Confirm access and payment with us ahead of time.")]),
 dict(slug="debris-removal", name="Debris Removal", blurb="Construction, remodel, storm and yard debris cleared out fast.", icon="02",
  intro="Remodels, storms and yard projects leave a mess. We haul away construction scraps, drywall, lumber, branches and general debris so your site is clear.",
  items=["Remodel and construction debris", "Drywall, lumber and flooring", "Storm and yard debris", "Fence, deck and shed teardown waste", "Branches and brush", "Flood-damaged materials"],
  faq=[("Do you take construction debris?", "Yes, within reason. Heavy materials like concrete or dirt are priced by the load."), ("Can you clean up after a storm?", "Yes. We haul limbs and damaged items once they are on the ground."), ("Do I need a dumpster?", "No. We bring the truck and the crew.")]),
 dict(slug="hoarder-cleanouts", name="Hoarder Cleanouts", blurb="Respectful, thorough cleanouts for heavily cluttered homes.", icon="03",
  intro="Heavy-clutter and hoarding cleanouts need patience and discretion. We work respectfully, set aside what you want to keep, and clear the rest efficiently.",
  items=["Whole-home heavy clutter", "Sorting items to keep", "Furniture, clothing and household goods", "Trash and debris", "Garage and outbuildings", "Cleanouts for families and property managers"],
  faq=[("Is this confidential?", "We treat every home with discretion and respect."), ("Can we keep certain items?", "Absolutely. Walk through with our crew first and mark what stays."), ("How long does it take?", "It depends on size. We will give you a realistic estimate after seeing photos.")]),
 dict(slug="appliance-removal", name="Appliance Removal", blurb="Refrigerators, washers, dryers, stoves and more removed.", icon="04",
  intro="Heavy appliances are hard to move and awkward to dispose of. We lift and haul away refrigerators, washers, dryers, ranges, dishwashers and more.",
  items=["Refrigerators and freezers", "Washers and dryers", "Stoves and ovens", "Dishwashers and microwaves", "Water heaters", "Window AC units"],
  faq=[("Do you disconnect appliances?", "Please disconnect water, gas and power first. We handle the lifting and hauling."), ("Do you recycle?", "Metal appliances are recycled where possible."), ("Can you install a new one?", "Yes, ask about our appliance installation service.")]),
 dict(slug="furniture-removal", name="Furniture Removal", blurb="Couches, mattresses, dressers, tables and more picked up.", icon="05",
  intro="Old couches, sleeper sofas, dressers, mattresses and dining sets are bulky and heavy. We pick them up from any room or floor and haul them off.",
  items=["Couches, sectionals and recliners", "Mattresses and box springs", "Dressers and bed frames", "Dining tables and chairs", "Desks and bookcases", "Patio furniture"],
  faq=[("Do you take furniture from upstairs?", "Yes, from any floor."), ("Do you take mattresses?", "Yes, all sizes."), ("Can you pick up a single item?", "Yes. Text a photo for a firm price.")]),
 dict(slug="appliance-installation", name="Appliance Installation", blurb="We haul away the old appliance and install the new one.", icon="06",
  intro="Replacing an appliance? We remove the old one and set up the new one in the same visit, saving you a second trip and a second crew.",
  items=["Washer and dryer installation", "Refrigerator placement and hookup", "Dishwasher and range installation", "Old appliance haul-away", "Delivery-day coordination", "Basic hookups where code allows"],
  faq=[("Do you haul away the old one?", "Yes. Removal is part of the visit."), ("Do you supply the new appliance?", "No. You supply the appliance and we install it."), ("What hookups do you do?", "Standard hookups. Call us for anything specialized.")]),
 dict(slug="local-moving", name="Local Moving", blurb="Local moves with a crew that handles the heavy lifting.", icon="07",
  intro="Moving across town or to the next suburb? Our crew loads, hauls and unloads, and we can take along the stuff you no longer want in the same trip.",
  items=["House and apartment moves", "Single-room moves", "Furniture and appliance moves", "Loading and unloading help", "Haul-away of unwanted items", "Storage-unit moves"],
  faq=[("How is moving priced?", "Text us details for a firm price."), ("Can you remove junk during a move?", "Yes, ask us to take what you do not want."), ("Do you move heavy items?", "Yes, including appliances and large furniture.")]),
 dict(slug="long-distance-moving", name="Long-Distance Moving", blurb="Moves beyond the Houston area, handled start to finish.", icon="08",
  intro="Relocating farther away? We help with loading and long-distance hauling. Call us with your move date and destination for a quote.",
  items=["Out-of-city and out-of-state moves", "Loading and unloading", "Large furniture and appliances", "Whole-house moves", "Move-out cleanout of leftovers", "Flexible scheduling"],
  faq=[("How do I get a quote?", "Call (346) 413-9644 with your date, size and destination."), ("Can you clear out what I am leaving?", "Yes, we can haul away what you are not taking."), ("Do you handle packing?", "Ask us about your needs and we will tell you what we can do.")]),
 dict(slug="trampoline-removal", name="Trampoline Removal", blurb="Trampolines taken down and hauled away, including damaged ones.", icon="09",
  intro="Old, rusted or storm-damaged trampolines are awkward to take apart. We disassemble and haul away trampolines of every size, safety nets included.",
  items=["Backyard trampolines", "Safety nets and enclosures", "Springs, mats and frames", "Storm-damaged trampolines", "In-ground and above-ground units", "Other playground equipment"],
  faq=[("Do you take them apart?", "Yes. We disassemble and haul everything."), ("Can you remove one blown into a yard?", "Yes, including storm-damaged ones."), ("Do you also take swing sets?", "Yes, ask about playsets and other backyard equipment.")]),
 dict(slug="basketball-goal-removal", name="Basketball Goal Removal", blurb="Portable and in-ground basketball goals removed and hauled.", icon="10",
  intro="Old basketball goals, portable bases and in-ground poles are heavy and hard to move. We remove them completely, including concrete bases when needed.",
  items=["Portable basketball goals", "In-ground goals and poles", "Backboards and rims", "Water and sand bases", "Concrete anchor removal (priced by load)", "Other backyard sports equipment"],
  faq=[("Can you remove an in-ground goal?", "Yes. Call for a quote because concrete is priced by weight."), ("Do you take portable goals?", "Yes, with the base."), ("Can you remove other sports equipment?", "Yes, ask us.")]),
]
